
insert into Division (id, name, headingInSchoolList) values ('divB', 'Division B', 'Elementary, Middle, and Junior High Schools (Division B):');
insert into Division (id, name, headingInSchoolList) values ('divC', 'Division C', 'High Schools (Division C):');
insert into Ethnicity (id, name) values ('amerNative', 'American Indian or Alaskan Native');
insert into Ethnicity (id, name) values ('asian', 'Asian');
insert into Ethnicity (id, name) values ('pacIslander', 'Pacific Islander');
insert into Ethnicity (id, name) values ('white', 'White');
insert into Ethnicity (id, name) values ('hispanic', 'Hispanic or Latino');
insert into Ethnicity (id, name) values ('black', 'Black or African American');
insert into Ethnicity (id, name) values ('zOther', 'Other');
insert into Ethnicity (id, name) values ('zzNoAnswer', 'Decline to Participate');
insert into GenderIdentity (id, name) values ('female', 'Female');
insert into GenderIdentity (id, name) values ('male', 'Male');
insert into GenderIdentity (id, name) values ('zzNoAnswer', 'Decline to Participate');
insert into LegalGuardianStatus (id, name) values ('guardian', 'I am the legal guardian of the competitor, and thus legally authorized to give these permissions.');
insert into LegalGuardianStatus (id, name) values ('self', 'I am 18 years of age, and thus legally authorized to give these permissions for myself.');
insert into LegalGuardianStatus (id, name) values ('zNotAuthorized', 'Neither of the above &mdash; please refer this to the appropriate person.  Registration will not be accepted otherwise.');
insert into StudentEntryDisposition (id, name, userAccountTypeId) values ('coachDup', 'Duplicate student entry', '1');
insert into StudentEntryDisposition (id, name, userAccountTypeId) values ('adminDup', 'Duplicate student entry (verified)', '0');
insert into StudentEntryDisposition (id, name, userAccountTypeId) values ('coachBadEntry', 'Improperly completed student entry', '1');
insert into StudentEntryDisposition (id, name, userAccountTypeId) values ('adminBadEntry', 'Improperly completed student entry (verified)', '0');
insert into StudentEntryDisposition (id, name, userAccountTypeId) values ('coachNotMySchool', 'This student entry is not for my school', '1');
insert into TournamentStatus (id, name) values ('frozen', 'Frozen to all changes');
insert into TournamentStatus (id, name) values ('frozenToCoachesNotParents', 'Frozen to coaches but not parents');
insert into TournamentStatus (id, name) values ('teamNamesFrozen', 'Frozen to team name changes');
insert into TournamentStatus (id, name) values ('open', 'Open to all changes');
insert into TournamentType (id, name) values ('regional', 'Regional');
insert into TournamentType (id, name) values ('state', 'State');
insert into UserAccountType (id, name) values ('admin', 'Admin');
insert into UserAccountType (id, name) values ('coach', 'Coach');
